# Usign the Clean Blog theme

title: Sparsity4PSL
author: sparsity4psl
email: nicolas.keriven@ens.fr
description: Sparsity4PSL Summer School
baseurl: ""
url: "http://sparsity4psl.github.io/"
github_username:  sparsity4psl

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Sparsity4PSL
gems:
  - jekyll-feed
  - jekyll-paginate
